name: Deploy my website
on:
  push:
    branches:
      - main
      - workspace/Sudip
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to remote vm
        run: |
            echo "Deploying to remote vm"