name: Deploy my website
on:
  push:
    branches:
      - main
      - prem
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup ssh host
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOST_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Deploy to nginx
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} <<EOF
          cd /home/ubuntu/devops-workshop-ft
          git checkout ${{ github.ref_name }}
          git pull
          # Update env
          sudo cp website/index.html /var/www/html
          sudo systemctl restart nginx
          EOF